openapi: 3.0.0
info:
  title: User API
  description: API para gerenciamento de usuários
  version: 1.0.0
servers:
  - url: https://api-peixes.vercel.app
paths:
  /users:
    post:
      summary: Cria um novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Usuário criado com sucesso
        '400':
          description: Requisição inválida
        '500':
          description: Erro interno do servidor
  /users/{userId}:
    get:
      summary: Retorna um usuário pelo ID
      parameters:
        - name: userId
          in: path
          required: true
          description: ID do usuário a ser retornado
          schema:
            type: string
      responses:
        '200':
          description: Usuário encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  email:
                    type: string
        '404':
          description: Usuário não encontrado
        '500':
          description: Erro interno do servidor
